# This rule is not used by the project ai-gateway-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the agentic-layer.ai.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ai-gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: aigatewayclass-editor-role
rules:
- apiGroups:
  - agentic-layer.ai
  resources:
  - aigatewayclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentic-layer.ai
  resources:
  - aigatewayclasses/status
  verbs:
  - get
