apiVersion: agentic-layer.ai/v1alpha1
kind: AiGateway
metadata:
  labels:
    app.kubernetes.io/name: ai-gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: my-litellm
spec:
  aiGatewayClassName: litellm
  aiModels:
    - name: gpt-3.5-turbo
      provider: openai
    - name: gemini-1.5-pro
      provider: gemini
